name: CD Back-end (TEST)

on:
  push:
    branches:
      - 'test'
    paths:
      - 'Backend/adotapet/**'
  pull_request:
    paths:
      - 'Backend/adotapet/**'
  workflow_call:

jobs:

  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/test-ci-backend-main.yml
    
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Railway
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalação do cliente Railway
        run: npm install -g @railway/cli
      - name: Deploy
        working-directory: Backend/adotapet/
        run: railway up --detach --service adota-pet-test
        env:
          RAILWAY_TOKEN: ${{ secrets.ADOTA_PET_TOKEN_TEST }}
