name: CI Back-end (TEST)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Backend/adotapet/**'
  pull_request:
    paths:
      - 'Backend/adotapet/**'
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Test
        working-directory: Backend/adotapet/
        run: mvn --activate-profiles prod-test test
  prod-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Package
        working-directory: Backend/adotapet/
        run: mvn --activate-profiles prod-test -DskipTests package
